approve_by_comment: true
approve_regex: '^(Reviewed|Approved|LGTM)'
reject_regex: '^Rejected'
reset_on_push: false
reviewers:
  required: 1
  members:
    - hjiang
    - jwfing
    - leeyeh
    - myleslee
    - sparanoid
    - sunchanglong
    - wujun4code
  name: default
